// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: classrooms.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const setStudentClassroom = `-- name: SetStudentClassroom :exec
INSERT INTO classrooms (room_id, student_id)
VALUES ($1, $2)
`

type SetStudentClassroomParams struct {
	RoomID    uuid.UUID
	StudentID uuid.UUID
}

func (q *Queries) SetStudentClassroom(ctx context.Context, arg SetStudentClassroomParams) error {
	_, err := q.db.ExecContext(ctx, setStudentClassroom, arg.RoomID, arg.StudentID)
	return err
}
