// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: collection_meta.sql

package database

import (
	"context"
	"time"
)

const getCollectionMeta = `-- name: GetCollectionMeta :one
SELECT updated_at FROM collection_meta
WHERE name = $1
`

func (q *Queries) GetCollectionMeta(ctx context.Context, name string) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getCollectionMeta, name)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}

const updateCollectionMeta = `-- name: UpdateCollectionMeta :exec
UPDATE collection_meta
SET updated_at = NOW()
WHERE name = $1
`

func (q *Queries) UpdateCollectionMeta(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, updateCollectionMeta, name)
	return err
}
