// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Classroom struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	RoomID    uuid.UUID
	StudentID uuid.UUID
}

type CollectionMetum struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Value     string
}

type Room struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}

type Student struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Nip         int32
	Name        string
	Email       string
	Year        int32
	RoomID      uuid.UUID
	StudyPlanID uuid.UUID
	PhoneNumber string
	Nim         string
}

type StudyPlan struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Semester  int32
	Major     string
}
