// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Classroom struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	RoomID    uuid.UUID
	StudentID uuid.UUID
}

type CollectionMetum struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Value     string
}

type Room struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}

type Session struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	LastActivity time.Time
	SessionID    string
	UserID       uuid.UUID
	IsRevoked    bool
	ExpireAt     time.Time
}

type Student struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Nip         string
	Name        string
	Email       string
	Year        int32
	RoomID      uuid.UUID
	StudyPlanID uuid.UUID
	PhoneNumber string
	Nim         string
	DateOfBirth time.Time
	UserID      uuid.UUID
}

type StudyPlan struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Semester  int32
	Major     string
}

type User struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Email        string
	PasswordHash string
}

type UserRole struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	Role      string
}
