// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: study_plans.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getStudyPlan = `-- name: GetStudyPlan :one
SELECT id, created_at, updated_at, semester, major FROM study_plans
WHERE semester = $1 AND major = $2
`

type GetStudyPlanParams struct {
	Semester int32
	Major    string
}

func (q *Queries) GetStudyPlan(ctx context.Context, arg GetStudyPlanParams) (StudyPlan, error) {
	row := q.db.QueryRowContext(ctx, getStudyPlan, arg.Semester, arg.Major)
	var i StudyPlan
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Semester,
		&i.Major,
	)
	return i, err
}

const getStudyPlanById = `-- name: GetStudyPlanById :one
SELECT id, created_at, updated_at, semester, major FROM study_plans
WHERE id = $1
`

func (q *Queries) GetStudyPlanById(ctx context.Context, id uuid.UUID) (StudyPlan, error) {
	row := q.db.QueryRowContext(ctx, getStudyPlanById, id)
	var i StudyPlan
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Semester,
		&i.Major,
	)
	return i, err
}
