// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_roles.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUserRoles = `-- name: CreateUserRoles :one
INSERT INTO user_roles (user_id, role)
VALUES ($1, $2)
RETURNING id, created_at, updated_at, user_id, role
`

type CreateUserRolesParams struct {
	UserID uuid.UUID
	Role   string
}

func (q *Queries) CreateUserRoles(ctx context.Context, arg CreateUserRolesParams) (UserRole, error) {
	row := q.db.QueryRowContext(ctx, createUserRoles, arg.UserID, arg.Role)
	var i UserRole
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Role,
	)
	return i, err
}

const getUserRolesByUserID = `-- name: GetUserRolesByUserID :many
SELECT id, created_at, updated_at, user_id, role FROM user_roles
WHERE user_id = $1
ORDER BY role ASC
`

func (q *Queries) GetUserRolesByUserID(ctx context.Context, userID uuid.UUID) ([]UserRole, error) {
	rows, err := q.db.QueryContext(ctx, getUserRolesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserRole
	for rows.Next() {
		var i UserRole
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
